import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokenRoot = resolve(projectRoot, 'design-tokens')

const [colors, radii] = await Promise.all([
  readFile(resolve(tokenRoot, 'color-tokens.json'), 'utf8').then(JSON.parse),
  readFile(resolve(tokenRoot, 'border-radius-tokens.json'), 'utf8').then(JSON.parse),
])

function collectTokens(node, path = []) {
  return Object.entries(node).flatMap(([key, value]) => {
    if (key.startsWith('$')) return []
    const nextPath = [...path, key]
    if (value && typeof value === 'object' && '$value' in value) {
      return [[nextPath.join('-'), value.$value]]
    }
    return value && typeof value === 'object' ? collectTokens(value, nextPath) : []
  })
}

const colorEntries = collectTokens(colors).map(([name, value]) => [name, value.hex])
const radiusEntries = collectTokens(radii).map(([name, value]) => [
  name.replace(/^radius-/, ''),
  `${value}px`,
])

const rootVariables = [
  ...colorEntries.map(([name, value]) => `  --token-color-${name}: ${value};`),
  ...radiusEntries.map(([name, value]) => `  --token-radius-${name}: ${value};`),
].join('\n')

const themeVariables = [
  ...colorEntries.map(([name]) => `  --color-${name}: var(--token-color-${name});`),
  ...radiusEntries.map(([name]) => `  --radius-${name}: var(--token-radius-${name});`),
].join('\n')

const output = `/* Generated by npm run tokens. Edit design-tokens/*.json instead. */
:root {
${rootVariables}
}

@theme inline {
${themeVariables}
}
`

await writeFile(resolve(projectRoot, 'src/styles/generated-tokens.css'), output)
const colorModule = `/* Generated by npm run tokens. Edit design-tokens/color-tokens.json instead. */\n${colorEntries.map(([name, value]) => {
  const identifier = `color${name.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('')}`
  return `export const ${identifier} = '${value}'`
}).join('\n')}\n`
await writeFile(resolve(projectRoot, 'src/styles/generated-colors.ts'), colorModule)
console.log(`Generated ${colorEntries.length + radiusEntries.length} design tokens.`)
